#!/bin/sh

#
# Usage: deploy-grid-job <script filename> <jar filename> [data filenames]
#

GRID_SERVER=ostrich1
LOGIN_SERVER=login.csee.ogi.edu
USER=dunlopa
GRID_HOME=/g/$USER

JOB_NAME=`basename $1 | sed -e s/^grid-//`
echo $JOB_NAME

TMP=/tmp/grid-tmp

# Create temporary directory
rm -rf $TMP
mkdir $TMP

# Create the tarball
cp -p $* $TMP
cd $TMP
tar czvf $JOB_NAME.tar.gz *

# Deploy the tarfile to the grid server
scp $JOB_NAME.tar.gz $USER@$LOGIN_SERVER:~/tmp
ssh $USER@$LOGIN_SERVER "scp ~/tmp/$JOB_NAME.tar.gz $USER@$GRID_SERVER:~/tmp; rm ~/tmp/$JOB_NAME.tar.gz"

# Create a job directory and extract the tarfile into it.
ssh $USER@$LOGIN_SERVER ssh $USER@$GRID_SERVER "\"mkdir -p $GRID_HOME/grid_jobs/$JOB_NAME; cd $GRID_HOME/grid_jobs/$JOB_NAME; tar zxf $GRID_HOME/tmp/$JOB_NAME.tar.gz\""

# Clean up
cd -
rm -rf $TMP